1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[ [5, 5, 5], [5, 5, 5], [5, 5, 5] ]

In [1]:
import numpy as np

def solve(dimensions, value):
    # Create the NumPy array filled with the given value
    array = np.full(dimensions, value)
    return array

# Example usage
result = solve((3, 3), 5)
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [2]:
def sum_arrays(*arrays):
    # Check if at least one array is provided
    if len(arrays) == 0:
        raise ValueError("At least one array must be provided.")

    # Check if all arrays have the same shape
    shape = arrays[0].shape
    if any(arr.shape != shape for arr in arrays):
        raise ValueError("All arrays must have the same shape.")

    # Perform element-wise sum of the arrays
    result = np.sum(arrays, axis=0)

    return result

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.array([[9, 10], [11, 12]])

result = sum_arrays(array1, array2, array3)
print(result)

[[15 18]
 [21 24]]


3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
[ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] top_left_sub_matrix (matrix, 2, 2) -> should return: [ [1, 2] [4, 5] ]

In [3]:
def top_left_sub_matrix(matrix, N, M):
    # Extract the top-left submatrix
    sub_matrix = matrix[:N, :M]
    return sub_matrix

# Example usage
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
result = top_left_sub_matrix(matrix, 2, 2)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
[ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed) [ [5, 6] [8, 9] ]

In [6]:
import numpy as np

def sub_matrix(matrix, N, M):
    # Get the dimensions of the original matrix
    rows, cols = matrix.shape

    # Calculate the starting indices for the submatrix
    start_row = rows - N
    start_col = cols - M

    # Extract the bottom-right submatrix
    sub_matrix = matrix[start_row:, start_col:]
    return sub_matrix

# Example usage
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = sub_matrix(matrix, 2,2)
print(result)


[[5 6]
 [8 9]]


5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
[1, 1, 1] solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0}

In [7]:
import numpy as np

def solution(arr):
    # Calculate the mean and standard deviation
    mean_value = np.mean(arr)
    std_dev_value = np.std(arr)

    # Create the dictionary
    result = {'mean': mean_value, 'std_dev': std_dev_value}

    return result

# Example usage
array = np.array([1, 1, 1])
result = solution(array)
print(result)

{'mean': 1.0, 'std_dev': 0.0}
