1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [3]:
import numpy as np

matrix_array = np.arange(2, 11).reshape(3, 3)
print(matrix_array)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. For instance:
Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [5]:
arr_float =matrix_array.astype(float)
print("Array converted to a float type:")
print( arr_float)

Array converted to a float type:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


3. Write a Numpy program to append values to the end of an array. For instance:
Original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [6]:
original_array = np.array([10, 20, 30])
values_to_append = np.array([40, 50, 60, 70, 80, 90])
appended_array = np.append(original_array, values_to_append)
print("Original array:", original_array)
print("After append values to the end of the array:", appended_array)

Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [7]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
sumArray = array1 + array2
print("sumArray:", sumArray)

sumArray: [ 7  9 11 13 15]


5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array.

In [12]:
array1 = np.arange(10, 100, 10).reshape(3, 3)
print('array',array1)
first_row = array1[0, :]
first_row
last_element = array1[-1, -1]
print("Last element:", last_element)

array [[10 20 30]
 [40 50 60]
 [70 80 90]]
Last element: 90
